// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTVRE0dMmpnKhGYxaQmwQAsJaq8BrMB08',
    appId: '1:953638705477:web:997cc36d14d40a512b462c',
    messagingSenderId: '953638705477',
    projectId: 'shop-app-14723',
    authDomain: 'shop-app-14723.firebaseapp.com',
    storageBucket: 'shop-app-14723.firebasestorage.app',
    measurementId: 'G-QCQY7B97LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FnCT8KT0Ql0SYok7svabojNmQOp-xSI',
    appId: '1:953638705477:android:f14b7dc1390e2d9a2b462c',
    messagingSenderId: '953638705477',
    projectId: 'shop-app-14723',
    storageBucket: 'shop-app-14723.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA03uJs9ycr1JC0TMz1q7OQ7vKcA7yWpLU',
    appId: '1:953638705477:ios:8c4f00a65bd50adc2b462c',
    messagingSenderId: '953638705477',
    projectId: 'shop-app-14723',
    storageBucket: 'shop-app-14723.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA03uJs9ycr1JC0TMz1q7OQ7vKcA7yWpLU',
    appId: '1:953638705477:ios:8c4f00a65bd50adc2b462c',
    messagingSenderId: '953638705477',
    projectId: 'shop-app-14723',
    storageBucket: 'shop-app-14723.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTVRE0dMmpnKhGYxaQmwQAsJaq8BrMB08',
    appId: '1:953638705477:web:39d38c2ae8d1823a2b462c',
    messagingSenderId: '953638705477',
    projectId: 'shop-app-14723',
    authDomain: 'shop-app-14723.firebaseapp.com',
    storageBucket: 'shop-app-14723.firebasestorage.app',
    measurementId: 'G-NJR56173TK',
  );
}
